// Precompile blog MDX files into plain React components at build time.
//
// Why: the app rendered MDX via `new Function(code)` (see
// components/features/mdx/mdx-components.tsx). Cloudflare Workers forbids
// dynamic code generation, so post bodies could not render there.
// Compiling to static modules here (Node, at build time) removes all runtime eval.
//
// Mirrors the velite MDX pipeline (velite.config.ts) so output matches.
//
// Usage: node scripts/compile-mdx.mjs  (npm run mdx)
// Output: content/compiled/<slug>.jsx + content/compiled/index.ts
import { readdir, readFile, writeFile, mkdir } from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"
import matter from "gray-matter"
import { compile } from "@mdx-js/mdx"
import remarkMath from "remark-math"
import rehypeKatex from "rehype-katex"
import rehypeSlug from "rehype-slug"
import rehypePrettyCode from "rehype-pretty-code"
import rehypeAutolinkHeadings from "rehype-autolink-headings"

const root = path.dirname(fileURLToPath(import.meta.url))
const blogDir = path.join(root, "..", "content", "blog")
const outDir = path.join(root, "..", "content", "compiled")

async function* walk(dir) {
	for (const entry of await readdir(dir, { withFileTypes: true })) {
		const full = path.join(dir, entry.name)
		if (entry.isDirectory()) yield* walk(full)
		else if (entry.name.endsWith(".mdx")) yield full
	}
}

const files = []
for await (const f of walk(blogDir)) files.push(f)
if (files.length === 0) {
	console.log("No MDX files found, nothing to compile.")
	process.exit(0)
}

const entries = []
for (const file of files) {
	// slugAsParams, same as velite: path under content/blog, minus one .mdx
	const rel = path.relative(blogDir, file).replace(/\.mdx$/, "")
	const { content } = matter(await readFile(file, "utf8"))

	const compiled = await compile(content, {
		outputFormat: "program",
		development: false,
		remarkPlugins: [remarkMath],
		rehypePlugins: [
			rehypeSlug,
			[rehypePrettyCode, { theme: "github-dark" }],
			[
				rehypeAutolinkHeadings,
				{
					behavior: "wrap",
					properties: {
						className: ["subheading-anchor"],
						ariaLabel: "Link to section",
					},
				},
			],
			rehypeKatex,
		],
	})

	const outFile = path.join(outDir, `${rel}.jsx`)
	await mkdir(path.dirname(outFile), { recursive: true })
	await writeFile(outFile, String(compiled))

	const varName = "Post_" + rel.replace(/[^a-zA-Z0-9]/g, "_")
	const importPath = `./${rel}.jsx`
	entries.push({ slug: rel, varName, importPath })
	console.log(`compiled ${rel}.mdx`)
}

const index = `// GENERATED by scripts/compile-mdx.mjs — do not edit by hand.
${entries.map((e) => `import ${e.varName} from "${e.importPath}"`).join("\n")}

export const mdxComponents: Record<string, React.ComponentType<any>> = {
${entries.map((e) => `\t"${e.slug}": ${e.varName},`).join("\n")}
}
`
await writeFile(path.join(outDir, "index.ts"), index)
console.log(`wrote index.ts with ${entries.length} posts`)
