// GENERATED by scripts/compile-mdx.mjs — do not edit by hand.
import Post_animation_concepts from "./animation-concepts.jsx"
import Post_animation_essence from "./animation-essence.jsx"
import Post_automating_cv_link_google_drive_mdx from "./automating-cv-link-google-drive.mdx.jsx"
import Post_best_practice_naming_git_branch from "./best-practice-naming-git-branch.jsx"
import Post_binary_tree_cameras_greedy_dfs from "./binary-tree-cameras-greedy-dfs.jsx"
import Post_ce from "./ce.jsx"
import Post_code_blocks from "./code-blocks.jsx"
import Post_code_interview_crud_form from "./code-interview-crud-form.jsx"
import Post_cookie_transmission_issue_merna_aws from "./cookie-transmission-issue-merna-aws.jsx"
import Post_deployment_mern_netflix_clone_aws_ec2 from "./deployment-mern-netflix-clone-aws-ec2.jsx"
import Post_design_linked_list_straightforward_to_elegant from "./design-linked-list-straightforward-to-elegant.jsx"
import Post_detect_cycle_floyd_tortoise_hare_algorithm from "./detect-cycle-floyd-tortoise-hare-algorithm.jsx"
import Post_disappearing_props from "./disappearing-props.jsx"
import Post_domain_suspension_rebranding_netwatch from "./domain-suspension-rebranding-netwatch.jsx"
import Post_drag_drop_api from "./drag-drop-api.jsx"
import Post_dummy_head_design_pattern from "./dummy-head-design-pattern.jsx"
import Post_dynamic_start_link_logic from "./dynamic-start-link-logic.jsx"
import Post_elegant_array_methods_in_react from "./elegant-array-methods-in-react.jsx"
import Post_event_loop from "./event-loop.jsx"
import Post_express_routing_conflict from "./express-routing-conflict.jsx"
import Post_fh from "./fh.jsx"
import Post_file_api from "./file-api.jsx"
import Post_fileUpload from "./fileUpload.jsx"
import Post_four_sum_algorithm_one_character_bug from "./four-sum-algorithm-one-character-bug.jsx"
import Post_from_2sum_to_ksum_recursive_optimization from "./from-2sum-to-ksum-recursive-optimization.jsx"
import Post_function_naming from "./function-naming.jsx"
import Post_github_markdown from "./github-markdown.jsx"
import Post_graphql_vs_rest from "./graphql-vs-rest.jsx"
import Post_hello_world from "./hello-world.jsx"
import Post_integrating_stripe_payment_elements_and_nextjs_14 from "./integrating-stripe-payment-elements-and-nextjs-14.jsx"
import Post_integration_testing from "./integration-testing.jsx"
import Post_javascript_array_initialization_pitfalls from "./javascript-array-initialization-pitfalls.jsx"
import Post_javascript_array_pitfalls_nums_negative_index_3sum from "./javascript-array-pitfalls-nums-negative-index-3sum.jsx"
import Post_javascript_linkedlist_classes_vs_factories from "./javascript-linkedlist-classes-vs-factories.jsx"
import Post_js_symbol_usage from "./js-symbol-usage.jsx"
import Post_knapsack_problem_complete_guide from "./knapsack-problem-complete-guide.jsx"
import Post_mastering_agentic_coding_claude_code_deeplearning_ai from "./mastering-agentic-coding-claude-code-deeplearning-ai.jsx"
import Post_next_blog_code_copy_button from "./next-blog-code-copy-button.jsx"
import Post_prop_drilling from "./prop-drilling.jsx"
import Post_react_debug_magic from "./react-debug-magic.jsx"
import Post_react_hooks from "./react-hooks.jsx"
import Post_react_junior_developer_interview from "./react-junior-developer-interview.jsx"
import Post_react_lifecycle_cats from "./react-lifecycle-cats.jsx"
import Post_react_movie_slider from "./react-movie-slider.jsx"
import Post_react_pagination from "./react-pagination.jsx"
import Post_react_projects_folder_structure from "./react-projects-folder-structure.jsx"
import Post_react_query_and_state_management from "./react-query-and-state-management.jsx"
import Post_react_query_guide from "./react-query-guide.jsx"
import Post_react_state_management from "./react-state-management.jsx"
import Post_remove_linked_list_elements from "./remove-linked-list-elements.jsx"
import Post_remove_nth_node_from_end_two_approaches from "./remove-nth-node-from-end-two-approaches.jsx"
import Post_resolve_vscode_jest_auto_launch from "./resolve-vscode-jest-auto-launch.jsx"
import Post_reverse_linked_list_two_pointers_three_nodes from "./reverse-linked-list-two-pointers-three-nodes.jsx"
import Post_sliding_window_minimum_subarray_sum from "./sliding-window-minimum-subarray-sum.jsx"
import Post_spiral_matrix_layer_strategy from "./spiral-matrix-layer-strategy.jsx"
import Post_sudoku_solver_backtracking_mrv_visualization from "./sudoku-solver-backtracking-mrv-visualization.jsx"
import Post_summon_component from "./summon-component.jsx"
import Post_swap_nodes_pairs_iterative_solutions from "./swap-nodes-pairs-iterative-solutions.jsx"
import Post_test from "./test.jsx"
import Post_two_pointers from "./two-pointers.jsx"
import Post_typescript_basic_types from "./typescript-basic-types.jsx"
import Post_typescript_data_types from "./typescript-data-types.jsx"
import Post_understanding_docker_port_mapping from "./understanding-docker-port-mapping.jsx"
import Post_understanding_lru_cache_in_javascript_and_react from "./understanding-lru-cache-in-javascript-and-react.jsx"
import Post_unique_binary_search_trees_dynamic_programming_catalan from "./unique-binary-search-trees-dynamic-programming-catalan.jsx"
import Post_unit_testing from "./unit-testing.jsx"
import Post_using_deepseek_r1_with_siliconflow from "./using-deepseek-r1-with-siliconflow.jsx"
import Post_worker_api from "./worker-api.jsx"

export const mdxComponents: Record<string, React.ComponentType<any>> = {
	"animation-concepts": Post_animation_concepts,
	"animation-essence": Post_animation_essence,
	"automating-cv-link-google-drive.mdx": Post_automating_cv_link_google_drive_mdx,
	"best-practice-naming-git-branch": Post_best_practice_naming_git_branch,
	"binary-tree-cameras-greedy-dfs": Post_binary_tree_cameras_greedy_dfs,
	"ce": Post_ce,
	"code-blocks": Post_code_blocks,
	"code-interview-crud-form": Post_code_interview_crud_form,
	"cookie-transmission-issue-merna-aws": Post_cookie_transmission_issue_merna_aws,
	"deployment-mern-netflix-clone-aws-ec2": Post_deployment_mern_netflix_clone_aws_ec2,
	"design-linked-list-straightforward-to-elegant": Post_design_linked_list_straightforward_to_elegant,
	"detect-cycle-floyd-tortoise-hare-algorithm": Post_detect_cycle_floyd_tortoise_hare_algorithm,
	"disappearing-props": Post_disappearing_props,
	"domain-suspension-rebranding-netwatch": Post_domain_suspension_rebranding_netwatch,
	"drag-drop-api": Post_drag_drop_api,
	"dummy-head-design-pattern": Post_dummy_head_design_pattern,
	"dynamic-start-link-logic": Post_dynamic_start_link_logic,
	"elegant-array-methods-in-react": Post_elegant_array_methods_in_react,
	"event-loop": Post_event_loop,
	"express-routing-conflict": Post_express_routing_conflict,
	"fh": Post_fh,
	"file-api": Post_file_api,
	"fileUpload": Post_fileUpload,
	"four-sum-algorithm-one-character-bug": Post_four_sum_algorithm_one_character_bug,
	"from-2sum-to-ksum-recursive-optimization": Post_from_2sum_to_ksum_recursive_optimization,
	"function-naming": Post_function_naming,
	"github-markdown": Post_github_markdown,
	"graphql-vs-rest": Post_graphql_vs_rest,
	"hello-world": Post_hello_world,
	"integrating-stripe-payment-elements-and-nextjs-14": Post_integrating_stripe_payment_elements_and_nextjs_14,
	"integration-testing": Post_integration_testing,
	"javascript-array-initialization-pitfalls": Post_javascript_array_initialization_pitfalls,
	"javascript-array-pitfalls-nums-negative-index-3sum": Post_javascript_array_pitfalls_nums_negative_index_3sum,
	"javascript-linkedlist-classes-vs-factories": Post_javascript_linkedlist_classes_vs_factories,
	"js-symbol-usage": Post_js_symbol_usage,
	"knapsack-problem-complete-guide": Post_knapsack_problem_complete_guide,
	"mastering-agentic-coding-claude-code-deeplearning-ai": Post_mastering_agentic_coding_claude_code_deeplearning_ai,
	"next-blog-code-copy-button": Post_next_blog_code_copy_button,
	"prop-drilling": Post_prop_drilling,
	"react-debug-magic": Post_react_debug_magic,
	"react-hooks": Post_react_hooks,
	"react-junior-developer-interview": Post_react_junior_developer_interview,
	"react-lifecycle-cats": Post_react_lifecycle_cats,
	"react-movie-slider": Post_react_movie_slider,
	"react-pagination": Post_react_pagination,
	"react-projects-folder-structure": Post_react_projects_folder_structure,
	"react-query-and-state-management": Post_react_query_and_state_management,
	"react-query-guide": Post_react_query_guide,
	"react-state-management": Post_react_state_management,
	"remove-linked-list-elements": Post_remove_linked_list_elements,
	"remove-nth-node-from-end-two-approaches": Post_remove_nth_node_from_end_two_approaches,
	"resolve-vscode-jest-auto-launch": Post_resolve_vscode_jest_auto_launch,
	"reverse-linked-list-two-pointers-three-nodes": Post_reverse_linked_list_two_pointers_three_nodes,
	"sliding-window-minimum-subarray-sum": Post_sliding_window_minimum_subarray_sum,
	"spiral-matrix-layer-strategy": Post_spiral_matrix_layer_strategy,
	"sudoku-solver-backtracking-mrv-visualization": Post_sudoku_solver_backtracking_mrv_visualization,
	"summon-component": Post_summon_component,
	"swap-nodes-pairs-iterative-solutions": Post_swap_nodes_pairs_iterative_solutions,
	"test": Post_test,
	"two-pointers": Post_two_pointers,
	"typescript-basic-types": Post_typescript_basic_types,
	"typescript-data-types": Post_typescript_data_types,
	"understanding-docker-port-mapping": Post_understanding_docker_port_mapping,
	"understanding-lru-cache-in-javascript-and-react": Post_understanding_lru_cache_in_javascript_and_react,
	"unique-binary-search-trees-dynamic-programming-catalan": Post_unique_binary_search_trees_dynamic_programming_catalan,
	"unit-testing": Post_unit_testing,
	"using-deepseek-r1-with-siliconflow": Post_using_deepseek_r1_with_siliconflow,
	"worker-api": Post_worker_api,
}
